# Generated by Django 5.2.6 on 2025-09-08 15:56

import django.core.validators
import django.db.models.deletion
import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('emoji', models.CharField(max_length=100, verbose_name='Эмодзи')),
            ],
            options={
                'verbose_name': 'Ингредиенты',
                'verbose_name_plural': 'Ингредиенты',
            },
        ),
        migrations.CreateModel(
            name='ShavarmaStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('logo', models.ImageField(blank=True, default=None, null=True, upload_to='logo', verbose_name='Логотип')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('rating', myapp.models.RatingField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
                ('network', models.BooleanField(verbose_name='Сетевая')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_updated', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
            ],
            options={
                'verbose_name': 'Шаурмечная',
                'verbose_name_plural': 'Шаурмечные',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('spicy', models.BooleanField(verbose_name='Острый')),
                ('rating', myapp.models.RatingField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_updated', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('ingredients', models.ManyToManyField(blank=True, related_name='food', to='myapp.ingredients')),
                ('shavarma_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food', to='myapp.shavarmastore', verbose_name='Шаурмечная')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
            },
        ),
    ]
