# Generated by Django 5.2.5 on 2025-09-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_food_rating_alter_shavarmastore_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='shavarmastore',
            name='logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='logo', verbose_name='Логотип'),
        ),
    ]
