# Generated by Django 5.2.5 on 2025-08-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='food',
        ),
        migrations.AddField(
            model_name='food',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='food', to='myapp.ingredients'),
        ),
    ]
