# Generated by Django 5.2.5 on 2025-08-31 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_ingredients_food_food_ingredients'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'verbose_name': 'Блюдо', 'verbose_name_plural': 'Блюда'},
        ),
        migrations.AlterModelOptions(
            name='ingredients',
            options={'verbose_name': 'Ингредиенты', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AlterModelOptions(
            name='shavarmastore',
            options={'verbose_name': 'Шаурмечная', 'verbose_name_plural': 'Шаурмечные'},
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='food',
            name='rating',
            field=models.IntegerField(verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='food',
            name='shavarma_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food', to='myapp.shavarmastore', verbose_name='Шаурмечная'),
        ),
        migrations.AlterField(
            model_name='food',
            name='spicy',
            field=models.BooleanField(verbose_name='Острый'),
        ),
        migrations.AlterField(
            model_name='food',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='food',
            name='time_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Время обновления'),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='emoji',
            field=models.CharField(max_length=100, verbose_name='Эмодзи'),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='shavarmastore',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='shavarmastore',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='shavarmastore',
            name='network',
            field=models.BooleanField(verbose_name='Сетевая'),
        ),
        migrations.AlterField(
            model_name='shavarmastore',
            name='rating',
            field=models.IntegerField(verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='shavarmastore',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='shavarmastore',
            name='time_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Время обновления'),
        ),
    ]
