# Generated by Django 5.2.5 on 2025-08-31 08:00

import django.core.validators
import myapp.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_food_options_alter_ingredients_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='rating',
            field=myapp.models.RatingField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='shavarmastore',
            name='rating',
            field=myapp.models.RatingField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг'),
        ),
    ]
